{
 "title": "LogView",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "rp",
    "label": "Retension Policy",
    "query": {
     "query": "import \"types\"\r\nimport \"date\"\r\nstart = if types.isType(type:\"duration\", v: v.timeRangeStart) then time(v: int(v: v.timeRangeStart) + int(v: v.timeRangeStop) - int(v: now())) else time(v: int(v: v.timeRangeStart) - int(v: now()))\r\nstop = time(v: 0)\r\nfrom(bucket: \"forever\")\r\n  |> range(start: 1900-01-01T00:00:00Z, stop: 1970-01-01T00:00:00Z)\r\n  |> filter(fn: (r) => r._measurement == \"rp_config\")\r\n  |> filter(fn: (r) => r._field == \"rp\")\r\n  |> range(start: start, stop: stop)\r\n  |> first()"
    }
   }
  ]
 },
 "panels": [
  { "title": "ViewLog", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "VOLTAGE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\ntmean0 = from(bucket: \"$rp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mean\")\r\n  |> filter(fn: (r) => r._field == \"pv_voltage_x10\" or r._field == \"battery_voltage_x10\" or r._field == \"load_voltage_x10\" )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value)/ 10.0, _field: strings.joinStr(arr: [strings.trimSuffix(v: r._field, suffix: \"_voltage_x10\")], v:\":\") }))\r\n\r\ntmean1 = from(bucket: \"$rp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mean\")\r\n  |> filter(fn: (r) => r._field == \"total_voltage_x100\" )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value)/ 100.0, _field: strings.joinStr(arr: [r.device], v:\":\") }))\r\n\r\ntmax0 = from(bucket: \"$rp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"max\")\r\n  |> filter(fn: (r) => r._field == \"pv_voltage_x10\" or r._field == \"battery_voltage_x10\" or r._field == \"load_voltage_x10\" )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value)/ 10.0, _field: strings.joinStr(arr: [strings.trimSuffix(v: r._field, suffix: \"_voltage_x10\"),\"max\"], v:\":\") }))\r\n\r\ntmax1 = from(bucket: \"$rp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"max\")\r\n  |> filter(fn: (r) => r._field == \"total_voltage_x100\" )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value)/ 100.0, _field: strings.joinStr(arr: [r.device,\"max\"], v:\":\") }))\r\n\r\ntmin0 = from(bucket: \"$rp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"min\")\r\n  |> filter(fn: (r) => r._field == \"pv_voltage_x10\" or r._field == \"battery_voltage_x10\" or r._field == \"load_voltage_x10\" )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / 10.0, _field: strings.joinStr(arr: [strings.trimSuffix(v: r._field, suffix: \"_voltage_x10\"),\"min\"], v:\":\") }))\r\n\r\ntmin1 = from(bucket: \"$rp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"min\")\r\n  |> filter(fn: (r) => r._field == \"total_voltage_x100\" )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value)/ 100.0, _field: strings.joinStr(arr: [r.device,\"min\"], v:\":\") }))\r\n\r\nunion(tables: [tmean0, tmax0, tmin0, tmean1, tmax1, tmin1])\r\n  |> sort(columns: [\"_field\"])\r\n  |> yield(name: \"a\")"
    }
   ]
  },
  {
   "title": "CAPACITY",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "amph" } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\ntmean0 = from(bucket: \"$rp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mean\")\r\n  |> filter(fn: (r) => r._field == \"remain_capacity_x100\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value)/ 100.0, _field: strings.joinStr(arr: [r.device], v:\":\") }))\r\n\r\ntmax0 = from(bucket: \"$rp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"max\")\r\n  |> filter(fn: (r) => r._field == \"remain_capacity_x100\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value)/ 100.0, _field: strings.joinStr(arr: [r.device,\"max\"], v:\":\") }))\r\n\r\ntmin0 = from(bucket: \"$rp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"min\")\r\n  |> filter(fn: (r) => r._field == \"remain_capacity_x100\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value)/ 100.0, _field: strings.joinStr(arr: [r.device,\"min\"], v:\":\") }))\r\n\r\ntlast1 = from(bucket: \"$rp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"last\")\r\n  |> filter(fn: (r) => r._field == \"nominal_capacity_x100\" )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value)/ 100.0, _field: strings.joinStr(arr: [r.device,\"nom\"], v:\":\") }))\r\n\r\nunion(tables: [tmean0, tmax0, tmin0, tlast1])\r\n  |> sort(columns: [\"_field\"])\r\n  |> yield(name: \"a\")"
    }
   ]
  },
  {
   "title": "STATUS",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "import \"bitwise\"\r\nimport \"strings\"\r\n\r\nnibble2hex = (v) => if bitwise.uand(a: uint(v: v), b: uint(v: 15)) == uint(v: 0) then \"0\" else if bitwise.uand(a: uint(v: v), b: uint(v: 15)) == uint(v: 1) then \"1\" else if bitwise.uand(a: uint(v: v), b: uint(v: 15)) == uint(v: 2) then \"2\" else if bitwise.uand(a: uint(v: v), b: uint(v: 15)) == uint(v: 3) then \"3\" else if bitwise.uand(a: uint(v: v), b: uint(v: 15)) == uint(v: 4) then \"4\" else if bitwise.uand(a: uint(v: v), b: uint(v: 15)) == uint(v: 5) then \"5\" else if bitwise.uand(a: uint(v: v), b: uint(v: 15)) == uint(v: 6) then \"6\" else if bitwise.uand(a: uint(v: v), b: uint(v: 15)) == uint(v: 7) then \"7\" else if bitwise.uand(a: uint(v: v), b: uint(v: 15)) == uint(v: 8) then \"8\" else if bitwise.uand(a: uint(v: v), b: uint(v: 15)) == uint(v: 9) then \"9\" else if bitwise.uand(a: uint(v: v), b: uint(v: 15)) == uint(v: 10) then \"A\" else if bitwise.uand(a: uint(v: v), b: uint(v: 15)) == uint(v: 11) then \"B\" else if bitwise.uand(a: uint(v: v), b: uint(v: 15)) == uint(v: 12) then \"C\" else if bitwise.uand(a: uint(v: v), b: uint(v: 15)) == uint(v: 13) then \"D\" else if bitwise.uand(a: uint(v: v), b: uint(v: 15)) == uint(v: 14) then \"E\" else \"F\"\r\nbyte2hex = (v) => strings.joinStr(arr: [\"0x\",nibble2hex(v: bitwise.urshift(a:uint(v: v) ,b: uint(v: 4))),nibble2hex(v: v)], v:\"\")\r\nword2hex = (v) => strings.joinStr(arr: [\"0x\",nibble2hex(v: bitwise.urshift(a:uint(v: v) ,b: uint(v: 12))),nibble2hex(v: bitwise.urshift(a:uint(v: v) ,b: uint(v: 8))),nibble2hex(v: bitwise.urshift(a:uint(v: v) ,b: uint(v: 4))),nibble2hex(v: v)], v:\"\")\r\n\r\nstatus = from(bucket: \"$rp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"last\")\r\n  |> filter(fn: (r) => r._field == \"load_status\" or r._field == \"charge_status\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n\r\ntab0 = status\r\n  |> filter(fn: (r) => r._field == \"load_status\")\r\n  |> map(fn: (r) => ({ r with _value: if r._value==0 then \"off\" else strings.joinStr(arr: [\"ON:\",byte2hex(v:r._value)], v:\"\"), _field: strings.trimSuffix(v: r._field, suffix: \"_status\")}))\r\n\r\ntab1 = status\r\n  |> filter(fn: (r) => r._field == \"charge_status\")\r\n  |> map(fn: (r) => ({ r with _value: if r._value==0 then \"NoCharge\" else if r._value==1 then \"Charging\" else if r._value==2 then \"Mppt\" else if r._value==3 then \"Equalizing\" else if r._value==4 then \"Float\" else if r._value==5 then \"Boost\"  else if r._value==6 then \"Limit\" else strings.joinStr(arr: [\"undef\",string(v:r._value)], v:\":\"), _field: strings.trimSuffix(v: r._field, suffix: \"_status\")}))\r\n\r\nunion(tables: [tab0, tab1])\r\n  |> sort(columns: [\"_field\"])\r\n  |> yield(name: \"a\")"
    }
   ]
  },
  {
   "title": "CELL VOLTAGE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\ntmean0 = from(bucket: \"$rp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mean\")\r\n  |> filter(fn: (r) => r._field == \"cell_voltage#00_x1000\" or r._field == \"cell_voltage#01_x1000\" or r._field == \"cell_voltage#02_x1000\" or r._field == \"cell_voltage#03_x1000\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value)/1000.0, _field: strings.joinStr(arr: [r.device,strings.trimSuffix(v: strings.trimPrefix(v: r._field, prefix: \"cell_voltage\"), suffix: \"_x1000\")], v:\"\") }))\r\n\r\ntmax0 = from(bucket: \"$rp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"max\")\r\n  |> filter(fn: (r) => r._field == \"cell_voltage#00_x1000\" or r._field == \"cell_voltage#01_x1000\" or r._field == \"cell_voltage#02_x1000\" or r._field == \"cell_voltage#03_x1000\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value)/1000.0, _field: strings.joinStr(arr: [r.device,strings.trimSuffix(v: strings.trimPrefix(v: r._field, prefix: \"cell_voltage\"), suffix: \"_x1000\"),\":max\"], v:\"\") }))\r\n\r\ntmin0 = from(bucket: \"$rp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"min\")\r\n  |> filter(fn: (r) => r._field == \"cell_voltage#00_x1000\" or r._field == \"cell_voltage#01_x1000\" or r._field == \"cell_voltage#02_x1000\" or r._field == \"cell_voltage#03_x1000\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value)/1000.0, _field: strings.joinStr(arr: [r.device,strings.trimSuffix(v: strings.trimPrefix(v: r._field, prefix: \"cell_voltage\"), suffix: \"_x1000\"),\":min\"], v:\"\") }))\r\n\r\nunion(tables: [tmean0, tmax0, tmin0])\r\n  |> sort(columns: [\"_field\"])\r\n  |> yield(name: \"a\")"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\ntmean0 = from(bucket: \"$rp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mean\")\r\n  |> filter(fn: (r) => r._field == \"battery_current_x100\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value)/ 100.0, _field: strings.joinStr(arr: [strings.trimSuffix(v: r._field, suffix: \"_current_x100\")], v:\"_\") }))\r\n\r\ntmax0 = from(bucket: \"$rp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"max\")\r\n  |> filter(fn: (r) => r._field == \"battery_current_x100\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value)/ 100.0, _field: strings.joinStr(arr: [strings.trimSuffix(v: r._field, suffix: \"_current_x100\"),\"max\"], v:\"_\") }))\r\n\r\ntmin0 = from(bucket: \"$rp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"min\")\r\n  |> filter(fn: (r) => r._field == \"battery_current_x100\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value)/ 100.0, _field: strings.joinStr(arr: [strings.trimSuffix(v: r._field, suffix: \"_current_x100\"),\"min\"], v:\"_\") }))\r\n\r\ntmean1 = from(bucket: \"$rp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mean\")\r\n  |> filter(fn: (r) => r._field == \"load_current_x100\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: float(v: -r._value)/ 100.0, _field: strings.joinStr(arr: [strings.trimSuffix(v: r._field, suffix: \"_current_x100\")], v:\"_\") }))\r\n\r\ntmax1 = from(bucket: \"$rp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"min\")\r\n  |> filter(fn: (r) => r._field == \"load_current_x100\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: float(v: -r._value)/ 100.0, _field: strings.joinStr(arr: [strings.trimSuffix(v: r._field, suffix: \"_current_x100\"),\"max\"], v:\"_\") }))\r\n\r\ntmin1 = from(bucket: \"$rp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"max\")\r\n  |> filter(fn: (r) => r._field == \"load_current_x100\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: float(v: -r._value)/ 100.0, _field: strings.joinStr(arr: [strings.trimSuffix(v: r._field, suffix: \"_current_x100\"),\"min\"], v:\"_\") }))\r\n\r\ntmean2 = from(bucket: \"$rp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mean\")\r\n  |> filter(fn: (r) => r._field == \"current_x100\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: float(v: -r._value)/ 100.0, _field: strings.joinStr(arr: [r.device], v:\"_\") }))\r\n\r\ntmax2 = from(bucket: \"$rp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"min\")\r\n  |> filter(fn: (r) => r._field == \"current_x100\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: float(v: -r._value)/ 100.0, _field: strings.joinStr(arr: [r.device,\"max\"], v:\"_\") }))\r\n\r\ntmin2 = from(bucket: \"$rp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"max\")\r\n  |> filter(fn: (r) => r._field == \"current_x100\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: float(v: -r._value)/ 100.0, _field: strings.joinStr(arr: [r.device,\"min\"], v:\"_\") }))\r\n\r\nunion(tables: [tmean0, tmax0, tmin0, tmean1, tmax1, tmin1, tmean2, tmax2, tmin2])\r\n  |> sort(columns: [\"_field\"])\r\n  |> yield(name: \"a\")"
    }
   ]
  },
  {
   "title": "EQUILIBRIUM",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "query": "import \"bitwise\"\r\nimport \"strings\"\r\n\r\nbor = (tables=<-, column=\"_value\") => tables\r\n    |> reduce(identity: {tmp: uint(v: 0),}, fn: (r, accumulator) => ({tmp: bitwise.uor(a: accumulator.tmp, b: uint(v: r._value)), }),)\r\n    |> rename(columns: {tmp: \"_value\"})\r\n\r\nequilibrium = from(bucket: \"$rp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"Bor\")\r\n  |> filter(fn: (r) => r._field == \"equilibrium\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: bor, createEmpty: false)\r\n\r\ntab0 = equilibrium\r\n  |> map(fn: (r) => ({ r with _value: if (bitwise.uand(a: uint(v: r._value), b: uint(v: 1)) != uint(v: 0)) then \"ON\" else \"off\", _field: strings.joinStr(arr: [r.device,\"#00\"], v:\"\")}))\r\n\r\ntab1 = equilibrium\r\n  |> map(fn: (r) => ({ r with _value: if (bitwise.uand(a: uint(v: r._value), b: uint(v: 2)) != uint(v: 0)) then \"ON\" else \"off\", _field: strings.joinStr(arr: [r.device,\"#01\"], v:\"\")}))\r\n\r\ntab2 = equilibrium\r\n  |> map(fn: (r) => ({ r with _value: if (bitwise.uand(a: uint(v: r._value), b: uint(v: 4)) != uint(v: 0)) then \"ON\" else \"off\", _field: strings.joinStr(arr: [r.device,\"#02\"], v:\"\")}))\r\n\r\ntab3 = equilibrium\r\n  |> map(fn: (r) => ({ r with _value: if (bitwise.uand(a: uint(v: r._value), b: uint(v: 8)) != uint(v: 0)) then \"ON\" else \"off\", _field: strings.joinStr(arr: [r.device,\"#03\"], v:\"\")}))\r\n\r\nunion(tables: [tab0, tab1, tab2, tab3])\r\n  |> sort(columns: [\"_field\"])\r\n  |> yield(name: \"a\")"
    }
   ]
  },
  {
   "title": "STATE OF CHARGE",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\ntmean0 = from(bucket: \"$rp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mean\")\r\n  |> filter(fn: (r) => r._field == \"state_of_charge\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _field: strings.joinStr(arr: [r.device], v:\"\") }))\r\n\r\ntmax0 = from(bucket: \"$rp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"max\")\r\n  |> filter(fn: (r) => r._field == \"state_of_charge\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _field: strings.joinStr(arr: [r.device,\":max\"], v:\"\") }))\r\n\r\ntmin0 = from(bucket: \"$rp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"min\")\r\n  |> filter(fn: (r) => r._field == \"state_of_charge\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _field: strings.joinStr(arr: [r.device,\":min\"], v:\"\") }))\r\n\r\nunion(tables: [tmean0, tmax0, tmin0])\r\n  |> sort(columns: [\"_field\"])\r\n  |> yield(name: \"a\")"
    }
   ]
  },
  {
   "title": "ALERT",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "query": "import \"bitwise\"\r\nimport \"strings\"\r\n\r\nbor = (tables=<-, column=\"_value\") => tables\r\n    |> reduce(identity: {tmp: uint(v: 0),}, fn: (r, accumulator) => ({tmp: bitwise.uor(a: accumulator.tmp, b: uint(v: r._value)), }),)\r\n    |> rename(columns: {tmp: \"_value\"})\r\n\r\nnibble2hex = (v) => if bitwise.uand(a: uint(v: v), b: uint(v: 15)) == uint(v: 0) then \"0\" else if bitwise.uand(a: uint(v: v), b: uint(v: 15)) == uint(v: 1) then \"1\" else if bitwise.uand(a: uint(v: v), b: uint(v: 15)) == uint(v: 2) then \"2\" else if bitwise.uand(a: uint(v: v), b: uint(v: 15)) == uint(v: 3) then \"3\" else if bitwise.uand(a: uint(v: v), b: uint(v: 15)) == uint(v: 4) then \"4\" else if bitwise.uand(a: uint(v: v), b: uint(v: 15)) == uint(v: 5) then \"5\" else if bitwise.uand(a: uint(v: v), b: uint(v: 15)) == uint(v: 6) then \"6\" else if bitwise.uand(a: uint(v: v), b: uint(v: 15)) == uint(v: 7) then \"7\" else if bitwise.uand(a: uint(v: v), b: uint(v: 15)) == uint(v: 8) then \"8\" else if bitwise.uand(a: uint(v: v), b: uint(v: 15)) == uint(v: 9) then \"9\" else if bitwise.uand(a: uint(v: v), b: uint(v: 15)) == uint(v: 10) then \"A\" else if bitwise.uand(a: uint(v: v), b: uint(v: 15)) == uint(v: 11) then \"B\" else if bitwise.uand(a: uint(v: v), b: uint(v: 15)) == uint(v: 12) then \"C\" else if bitwise.uand(a: uint(v: v), b: uint(v: 15)) == uint(v: 13) then \"D\" else if bitwise.uand(a: uint(v: v), b: uint(v: 15)) == uint(v: 14) then \"E\" else \"F\"\r\nbyte2hex = (v) => strings.joinStr(arr: [\"0x\",nibble2hex(v: bitwise.urshift(a:uint(v: v) ,b: uint(v: 4))),nibble2hex(v: v)], v:\"\")\r\nword2hex = (v) => strings.joinStr(arr: [\"0x\",nibble2hex(v: bitwise.urshift(a:uint(v: v) ,b: uint(v: 12))),nibble2hex(v: bitwise.urshift(a:uint(v: v) ,b: uint(v: 8))),nibble2hex(v: bitwise.urshift(a:uint(v: v) ,b: uint(v: 4))),nibble2hex(v: v)], v:\"\")\r\n\r\nstat = from(bucket: \"$rp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"Bor\")\r\n  |> filter(fn: (r) => r._field == \"alarm\" or r._field == \"protection_status\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: bor, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: word2hex(v: r._value), _field: r.device}))\r\n  |> sort(columns: [\"_field\"])\r\n  |> yield(name: \"a\")\r\n"
    }
   ]
  },
  {
   "title": "TEMPERATURE",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\ntmean0 = from(bucket: \"$rp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mean\")\r\n  |> filter(fn: (r) => r._field == \"controller_temperature_celsius\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _field: strings.joinStr(arr: [r.device], v:\"\") }))\r\n\r\ntmean1 = from(bucket: \"$rp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mean\")\r\n  |> filter(fn: (r) => r._field == \"ntc#00\" or r._field == \"ntc#01\" or r._field == \"ntc#02\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: (float(v: r._value)-2731.0)/10.0, _field: strings.joinStr(arr: [r.device,strings.trimPrefix(v: r._field, prefix: \"ntc\")], v:\"\") }))\r\n\r\ntmax0 = from(bucket: \"$rp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"max\")\r\n  |> filter(fn: (r) => r._field == \"controller_temperature_celsius\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _field: strings.joinStr(arr: [r.device,\":max\"], v:\"\") }))\r\n\r\ntmax1 = from(bucket: \"$rp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"max\")\r\n  |> filter(fn: (r) => r._field == \"ntc#00\" or r._field == \"ntc#01\" or r._field == \"ntc#02\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: (float(v: r._value)-2731.0)/10.0, _field: strings.joinStr(arr: [r.device,strings.trimPrefix(v: r._field, prefix: \"ntc\"),\":max\"], v:\"\") }))\r\n\r\ntmin0 = from(bucket: \"$rp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"min\")\r\n  |> filter(fn: (r) => r._field == \"controller_temperature_celsius\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _field: strings.joinStr(arr: [r.device,\":min\"], v:\"\") }))\r\n\r\ntmin1 = from(bucket: \"$rp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"min\")\r\n  |> filter(fn: (r) => r._field == \"ntc#00\" or r._field == \"ntc#01\" or r._field == \"ntc#02\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: (float(v: r._value)-2731.0)/10.0, _field: strings.joinStr(arr: [r.device,strings.trimPrefix(v: r._field, prefix: \"ntc\"),\":min\"], v:\"\") }))\r\n\r\nunion(tables: [tmean0, tmax0, tmin0, tmean1, tmax1, tmin1])\r\n  |> sort(columns: [\"_field\"])\r\n  |> yield(name: \"a\")"
    }
   ]
  },
  {
   "title": "FET",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "query": "import \"bitwise\"\r\nimport \"strings\"\r\n\r\nbor = (tables=<-, column=\"_value\") => tables\r\n    |> reduce(identity: {tmp: uint(v: 0),}, fn: (r, accumulator) => ({tmp: bitwise.uor(a: accumulator.tmp, b: uint(v: r._value)), }),)\r\n    |> rename(columns: {tmp: \"_value\"})\r\n\r\nfet_control = from(bucket: \"$rp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"Bor\")\r\n  |> filter(fn: (r) => r._field == \"fet_control\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: bor, createEmpty: false)\r\n\r\ntab0 = fet_control\r\n  |> map(fn: (r) => ({ r with _value: if (bitwise.uand(a: uint(v: r._value), b: uint(v: 1)) != uint(v: 0)) then \"ON\" else \"off\", _field: strings.joinStr(arr: [r.device,\"#Charge\"], v:\"\")}))\r\n\r\ntab1 = fet_control\r\n  |> map(fn: (r) => ({ r with _value: if (bitwise.uand(a: uint(v: r._value), b: uint(v: 2)) != uint(v: 0)) then \"ON\" else \"off\", _field: strings.joinStr(arr: [r.device,\"#Discharge\"], v:\"\")}))\r\n\r\nunion(tables: [tab0, tab1])\r\n  |> sort(columns: [\"_field\"])\r\n  |> yield(name: \"a\")"
    }
   ]
  }
 ]
}